name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Compile QuakeC code
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout QuakeC code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download FTEQCC
        run: |
          wget -q https://www.fteqcc.org/dl/fteqcc_linux64.zip
          unzip fteqcc_linux64.zip

      - name: Compile QuakeC code
        shell: bash
        run: |
          PROJECTS=(
            ad
            alkaline
            copper
            hipnotic
            id1
            progs_dump
            remobilize
            rerelease/quakec
            rerelease/quakec_ctf
            rerelease/quakec_hipnotic
            rerelease/quakec_mg1
            rerelease/quakec_rogue
            rogue
            smp/src
          )

          for project in ${PROJECTS[@]}; do
            echo ::group::$project
            ./fteqcc64 -src $project
            echo ::endgroup::
          done

      - name: List Directories
        if: always()
        shell: bash
        run: |
          git status
          ls -lR
