name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Compile QuakeC code
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout QuakeC code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Compile FTEQCC
        run: |
          mkdir fteqcc

          # The last commit that compile Alkaline without segmentation fault
          # See https://github.com/fte-team/fteqw/issues/328
          COMMIT=0df247d4c188133d5f8f309607d2278ebad4ce13

          cd fteqcc
          wget -q https://github.com/fte-team/fteqw/archive/$COMMIT.tar.gz
          tar -xf $COMMIT.tar.gz

          cd fteqw-$COMMIT
          cmake .
          cmake --build . --target fteqcc --parallel
          cp fteqcc ..

      - name: Compile QuakeC code
        shell: bash
        run: |
          PROJECTS=(
            ad
            alkaline
            copper
            hipnotic
            honey
            id1
            progs_dump/qc
            remobilize
            rerelease/quakec
            rerelease/quakec_hipnotic
            rerelease/quakec_mg1
            rerelease/quakec_rogue
            rogue
            smp/src
            zer
          )
          FTEQCC=./fteqcc/fteqcc

          for project in ${PROJECTS[@]}; do
            echo ::group::$project
            $FTEQCC -src $project
            echo ::endgroup::
          done

          # Special case to avoid compilation error in drake/thor.qc
          # where 'static' keyword is used as variable name
          echo ::group::drake
            $FTEQCC -src drake -Kno-static
          echo ::endgroup::

      - name: List Directories
        if: always()
        shell: bash
        run: |
          git status
          ls -lR
