name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Compile QuakeC code
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout QuakeC code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download FTEQCC
        run: |
          wget -q https://www.fteqcc.org/dl/fteqcc_linux64.zip
          unzip fteqcc_linux64.zip fteqcc64

      - name: Compile QuakeC code
        shell: bash
        run: |
          PROJECTS=(
            ad
            alkaline
            copper
            hipnotic
            honey
            id1
            progs_dump/qc
            remobilize
            rerelease/quakec
            rerelease/quakec_hipnotic
            rerelease/quakec_mg1
            rerelease/quakec_rogue
            rogue
            smp/src
            zer
          )

          for project in ${PROJECTS[@]}; do
            echo ::group::$project
            ./fteqcc64 -src $project
            echo ::endgroup::
          done

          # Special case to avoid compilation error in drake/thor.qc
          # where 'static' keyword is used as variable name
          echo ::group::drake
            ./fteqcc64 -src drake -Kno-static
          echo ::endgroup::

      - name: List Directories
        if: always()
        shell: bash
        run: |
          git status
          ls -lR
